### PR TITLE
Bots can send 10 embeds now

### PR DESCRIPTION
**Pull request by kakarot-dev**
Note: This will break for v12 users, I recommend u test this first as i havent done so

This is for v13

### CODE REVIEW

**Comment by kakarot-dev** [comment]
The thing works perfectly and is ready for review

If this pr is merged, and users are still using v12, they can use `npm i discordjs-paginate@0.0.5-bunnygirl` to use the v12 use

**Comment by kakarot-dev** [comment]
@maisans-maid pls review

**Comment by maisans-maid** [comment]
Will merge when the they officially release the v13 of the bot, which is expected on the end of this month

**Comment by kakarot-dev** [comment]
Oki then
Thanks

**Comment by kakarot-dev** [comment]
@maisans-maid can u merge this pls

**Pull request merged**
